### ISSUE TITLE
error TS1127: Invalid character error in ngentest generated spec file when using Jasmine/Karma

### ISSUE THREAD

**Issue by chalcrow** [allenhwkim/ngentest#17]
Hi Alan

Thanks again for your work - this looks like a great tool! I'm getting the following issue with an `ngentest` generated test, with Jasmine and Karma, when running ng test in the terminal:

error TS1127: Invalid character error 

Full details here:

https://stackoverflow.com/questions/57799360/error-ts1127-invalid-character-when-running-karma-tests-in-angular-7

I tried uninstalling and re-installing Jasmine + Karma, removing the `ngentest` generated file, building, then regenerating the spec file, doing an `npm run build`, then `ng test` - same issue. Here's exactly what I did when I uninstalled and re-installed:

npm uninstall karma-jasmine
npm uninstall karma
npm uninstall jasmine
npm uninstall jasmine-core
npm uninstall jasmine-spec-reporter
npm uninstall karma-jasmine-html-reporter

remove following from package.json

"@types/jasmine": "~3.3.12",
"@types/jasminewd2": "^2.0.6",

"karma-chrome-launcher": "~2.2.0",
"karma-cli": "~2.0.0",
"karma-coverage-istanbul-reporter": "^2.0.5",

npm install

-----

npm install karma-jasmine
npm install karma
npm install jasmine
npm install jasmine-core
npm install jasmine-spec-reporter
npm install karma-jasmine-html-reporter
npm install karma-chrome-launcher
npm install karma-cli
npm install karma-coverage-istanbul-reporter
npm install -save @types/jasmine
npm install -save @types/jasminewd2
npm i ngentest

npm install

remove app.component.spec.ts

npm run build
ng test (to verify that karma-jasmine is working correctly)

ngentest app.component.ts > app.component.spec.ts
npm run build
ng test

---

my package.json is now:

  "dependencies": {
    "@angular/animations": "^7.2.13",
    "@angular/common": "^7.2.13",
    "@angular/compiler": "^7.2.13",
    "@angular/core": "^7.2.13",
    "@angular/forms": "^7.2.15",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^7.2.13",
    "@angular/platform-browser-dynamic": "^7.2.13",
    "@angular/router": "^7.2.13",
    "@aspnet/signalr": "^1.1.4",
    "@ecotech/common-angular-dashboard-lib": "^7.0.2",
    "@ecotech/common-angular-widgets-lib": "^7.0.30",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.22",
    "@ngx-translate/i18n-polyfill": "^1.0.0",
    "@types/jasmine": "^3.4.0",
    "@types/jasminewd2": "^2.0.6",
    "bootstrap": "^4.3.1",
    "core-js": "^2.6.5",
    "font-awesome": "^4.7.0",
    "highcharts": "^7.1.1",
    "jasmine": "^3.4.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.3.0",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "ng2-dragula": "^1.5.0",
    "ngentest": "^0.4.1",
    "ngx-bootstrap": "^4.0.1",
    "ngx-toastr": "^10.0.2",
    "popper.js": "^1.15.0",
    "rxjs": "^6.5.1",
    "rxjs-compat": "^6.5.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular-devkit/core": "7.3.8",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/language-service": "^7.2.15",
    "@fortawesome/pro-light-svg-icons": "^5.10.2",
    "@fortawesome/pro-regular-svg-icons": "^5.10.2",
    "@fortawesome/pro-solid-svg-icons": "^5.10.2",
    "@types/node": "^11.13.7",
    "acorn": "^6.1.1",
    "codelyzer": "~5.0.0",
    "concurrently": "^4.1.2",
    "ncp": "^2.0.0",
    "ngx-i18nsupport": "^0.17.1",
    "protractor": "^5.4.2",
    "ts-node": "~8.1.0",
    "tslint": "^5.16.0",
    "typescript": "^3.2.4",
    "webpack-bundle-analyzer": "^3.3.2"
  }

**Comment by allenhwkim** [comment]
I haven't run this with Karma and Jasmine.
Can you make a small repo. to make your issue reproducible?

**Comment by chalcrow** [comment]
Hi Allen I may set that up although I'm going to try an alternative approach first. In the meantime, I inspected the .spec file in notepad++, stripped out everything except all `CRLF`, pasted back in - didnt' work

**Comment by linksach3** [comment]
Hi, How did you run ngentest with Jasmin/Karma. When i tried it, it created test files with Jest.

**Comment by allenhwkim** [comment]
Currently it only supports Jest. PR would be appreciated.

**Comment by allenhwkim** [comment]
now you can configure your test framework to karma using
https://github.com/allenhwkim/ngentest#full-example-httpsgithubcomallenhwkimngentestblobmasterngentestconfigjs
```
module.exports = {
  framework: 'karma', // or 'jest'
```
