### ISSUE TITLE
Invalid Typescript File

### ISSUE THREAD

**Issue by rajawatyagya** [allenhwkim/ngentest#25]
when i run  ngentest app.component.ts, i get:

Error. invalid typescript file. e.g., Usage $0 <tsFile> [options]

my ngentest.config.js file: 
```
const fs = require('fs');
const path = require('path');
const klassTemplate = fs.readFileSync(path.join(__dirname, 'src', 'class', 'class.template.ts.ejs'), 'utf8');
const componentTemplate = fs.readFileSync(path.join(__dirname, 'src', 'component', 'component.template.ts.ejs'), 'utf8');
const directiveTemplate = fs.readFileSync(path.join(__dirname, 'src', 'directive', 'directive.template.ts.ejs'), 'utf8');
const injectableTemplate = fs.readFileSync(path.join(__dirname, 'src', 'injectable', 'injectable.template.ts.ejs'), 'utf8');
const pipeTemplate = fs.readFileSync(path.join(__dirname, 'src', 'pipe', 'pipe.template.ts.ejs'), 'utf8');

module.exports = {
  framework: 'karma', // or 'jest'
  templates: {
    klass: klassTemplate,  // ejs contents read from file
    component: componentTemplate,
    directive: directiveTemplate,
    injectable: injectableTemplate,
    pipe: pipeTemplate
  },
  // necessary directives used for a component test
  directives: [
    'oneviewPermitted'
  ],
  // necessary pipes used for a component test
  pipes: [
    'translate', 'phoneNumber', 'safeHtml'
  ],
  // when convert to JS, some codes need to be replaced to work
  replacements: [ // some 3rd party module causes an error
    { from: 'require\\("html-custom-element"\\)', to: '{}'},
    { from: '^\\S+\\.define\\(.*\\);', to: ''} // some commands causes error
  ],
  // when constructor param type is as following, create a mock class with this properties
  // e.g. @Injectable() MockElementRef { nativeElement = {}; }
  providerMocks: {
    ElementRef: ['nativeElement = {};'],
    Router: ['navigate() {};'],
    Document: ['querySelector() {};'],
    HttpClient: ['post() {};'],
    TranslateService: ['translate() {};'],
    EncryptionService: [],
  },
  // when ngentest runs with a directory, include only these files
  includeMatch: [/(component|directive|pipe|service).ts/],
  // when ngentest runs with a directory, exclude these files
  excludeMatch: []
}
```

**Comment by allenhwkim** [comment]
Try this `$ ngentest ./app.component.ts`

**Comment by ThiloVoigt555** [comment]
I have this issue too. Providing the absolute path to the file did not help

**Comment by allenhwkim** [comment]
Can you provide your command line errors? I don't have this error(because I use Mac?)

**Comment by ThiloVoigt555** [comment]
Sure. Its not much though...
`Error. invalid typescript file. e.g., Usage $0 <tsFile> [options]`

**Comment by allenhwkim** [comment]
Hmm, I think this is Windows command line issue, which I haven't looked. 
Can anyone look at this and make a PR?

**Comment by ThiloVoigt555** [comment]
Oh right, I am using the git bash with Win10

**Comment by mohamed-attia** [comment]
i was getting the same error and when i provide the full path it is work with me (i am using windows 10)
or you can open the terminal with the current directory of the file you need to test and provide the command with the file name only (using vscode) => ngentest "filename"

**Comment by allenhwkim** [comment]
For Windows users, 
1. use git bash
2. or as @mohamed-attia mentioned, plz provide full path for windows users

**Comment by vinyyyyyyya** [comment]
> i was getting the same error and when i provide the full path it is work with me (i am using windows 10) or you can open the terminal with the current directory of the file you need to test and provide the command with the file name only (using vscode) => ngentest "filename"

can u please tell the steps i am getting confused

**Comment by subratbhola** [comment]
**even i am getting the same issue**
