### ISSUE TITLE
How do we fix exported functions?

### ISSUE THREAD

**Issue by t0n1n3** [allenhwkim/ngentest#34]
Hi,

I have a ts file in which I'm exporting some functions directly.
Example - 
```
export function routerTransitionRight() {
  return slideToRight();
}
```

I'm importing it in my component as
```
import { routerTransitionLeft } from './list.animations';
```

When testing for the component I'm getting the error
```
list_animations_1.routerTransitionRight is not a function
```

Any way to fix it?

**Comment by allenhwkim** [comment]
sorry, this repo. only target Angular ones. 
It still supports class structure, but not function one.
