### ISSUE TITLE
Cannot read property 'foreach' of undefined.

### ISSUE THREAD

**Issue by ybarbaria** [allenhwkim/ngentest#4]
I have this error when I try to use ngentest on directives, components ... 

> TypeError: Cannot read property 'forEach' of undefined
    at parseTypescript (C:\Users\ybarbaria\AppData\Roaming\npm\node_modules\ngentest\src\lib\parse-typescript.js:55:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Comment by allenhwkim** [comment]
It's odd. Your class does not have any properties?
https://github.com/allenhwkim/ngentest/blob/master/src/lib/parse-typescript.js#L55

**Comment by Kirylka** [comment]
+1

**Comment by Kirylka** [comment]
`import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';
import { upperFirst }  from 'lodash';

interface BreadcrumbItem {
  name: string;
  navigateCommands?: any[];
}

@Component({
  selector: 'app-performance-breadcrumbs',
  templateUrl: './breadcrumbs.component.html',
  styleUrls: ['./breadcrumbs.component.scss']
})
export class BreadcrumbsComponent {
  @Input() public items: BreadcrumbItem[];

  constructor(private router: Router) { }

  public handleNavigate(item: BreadcrumbItem) {
    if (item.navigateCommands) {
      this.router.navigate(item.navigateCommands);
    }
  }

  public getDisplayName(name) {
    return upperFirst(name);
  }
}
`

**Comment by StefanChristou** [comment]
+1

**Comment by amilaI** [comment]
+1

**Comment by allenhwkim** [comment]
Please post your directive example, so that I can experience the real bug.

**Comment by chauey** [comment]
Do we need constructor params and also properties that are initialized to something? Otherwise it will break. just declaring the property is not enough, need to set a value.

For me, this caused a problem
`declare var $: any;`

**Comment by allenhwkim** [comment]
This has been fixed. sorry for the long wait
