### ISSUE TITLE
Instructions local environment 

### ISSUE THREAD

**Issue by mikeRujevic** [allenhwkim/ngentest#40]
It would be nice to have instructions for local environment setup.

**Comment by allenhwkim** [comment]
I don't understand this and it seems README.md is not enough for @mikeRujevic 
Cans someone write instruction as a response?

**Comment by jacobmcgowan** [comment]
Hello @mikeRujevic, you can install it as a developer dependency using `npm install --save-dev ngentest`. Then you can add a configuration file named `ngentest.config.js` to your project's root folder.
