### ISSUE TITLE
In my case it failer because the model.

### ISSUE THREAD

**Issue by apozogar1** [allenhwkim/ngentest#45]
Hi,

In my case it failed because it not find the model:
![image](https://user-images.githubusercontent.com/61603778/108504785-bdde2a00-72b6-11eb-9513-e170a04d94b7.png)
![image](https://user-images.githubusercontent.com/61603778/108504860-dc442580-72b6-11eb-9b41-d2ebf11b40ca.png)

What it's the problem?

**Comment by allenhwkim** [comment]
I tested similar one, and it seems working for me.
If not working, plz use replacements(you can find in REAME.md) to modifiy code before generating test.

If still not working, create a simple component file which errored out for ngentest,  and paste it here, so that i can take a look.

**Comment by apozogar1** [comment]
Hi,

Now, it's generated but I need to change the relative path by his path:
Not generate this:
import { Porpuse, Ru } from '@app/model/rus.model';
Or:
import { Porpuse, Ru } from 'src/app/model/rus.model';

But with this path, yes:
import { Porpuse, Ru } from './../../../../model/rus.model';

It's posible to review this option?

**Comment by allenhwkim** [comment]
Try this in your ngentest.config.js

```
replacements: [
  { from: 'src\/app\/model\/rus\.model', to: ''}`
]
```

**Comment by apozogar1** [comment]
Yes, with this change worked.
Thanks.
