### ISSUE TITLE
Error generating for require-from-string

### ISSUE THREAD

**Issue by apozogar1** [allenhwkim/ngentest#46]
Hi again,

Of new, I have a problem, in this time, I throw for generate the path folder and it throw this exception:
![image](https://user-images.githubusercontent.com/61603778/108811968-815c4800-75ae-11eb-88ab-59843d705ed9.png)

What it's the problems?

Thanks for all.

**Comment by allenhwkim** [comment]
plz paste your code here. `import\import.component.ts`

`ngentest` does not work with Windows? I have never tested this under Windows env. I need help with Windows.

**Comment by apozogar1** [comment]
This it's my component, it's not unique, I think failed all the component:

`import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { TranslateService } from '@ngx-translate/core';
import { ToastrService } from 'ngx-toastr';
import { RuImport } from 'src/app/model/rus.model';
import { RusService } from 'src/app/services/rus.service';
import { SharedService } from 'src/app/shared/shared.service';
import { ViewAbstractComponent } from 'src/app/shared/view.abstract';
import Utils from 'src/app/utils/utils';

@Component({
  selector: 'app-import',
  templateUrl: './import.component.html',
})
export class ImportComponent extends ViewAbstractComponent implements OnInit {
  uploadedFiles: any[] = [];
  modalResume = false;
  listRus: Array<RuImport> = [];
  listRusOk: Array<RuImport> = [];
  listRusError: Array<RuImport> = [];
  numRus = 0;
  numRusOk = 0;
  numRusError = 0;
  map = new Map();

  constructor(
    public sharedService: SharedService,
    private rusService: RusService,
    private translateService: TranslateService,
    private router: Router,
    private toastrService: ToastrService
  ) {
    super(sharedService);
  }

  ngOnInit(): void {
    this.sharedService.setChangeMenu();
  }

  downloadTemplate(): void {
    this.rusService.downloadTemplateImport(this.translateService.currentLang).subscribe((blob: any) => {
      Utils.downloadObject(blob, 'template.xlsx');
    }, Utils.showErrorGeneric(this.toastrService, this.translateService));
  }

  uploadFile(event?: any): void {
    for (const file of event.files) {
      const fileObj = { state: 1, file, progress: 0, message: '' };
      this.uploadedFiles.push(fileObj);
      if (file.type !== 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') {
        fileObj.state = 3;
        fileObj.progress = 100;
        fileObj.message = 'rus.import.type_incorrect';
      } else {
        const interval = setInterval(() => {
          fileObj.progress = fileObj.progress + Math.floor(Math.random() * 10) + 1;
          if (fileObj.progress >= 99) {
            fileObj.state = 2;
            fileObj.progress = 99;
            clearInterval(interval);
          }
        }, 300);

        this.rusService.import(this.uploadedFiles[0].file).subscribe(
          (data: Array<RuImport>) => {
            this.map.set(fileObj, data);
            fileObj.state = 2;
            fileObj.progress = 100;
            clearInterval(interval);
          },
          (error: any) => {
            fileObj.state = 3;
            fileObj.message = 'rus.import.upload_error';
            fileObj.progress = 100;
            Utils.showErrorGeneric(this.toastrService, this.translateService);
          }
        );
      }
    }
  }

  deleteItemTable(file: any): void {
    this.uploadedFiles.splice(this.uploadedFiles.indexOf(file), 1);
    this.map.delete(file);
    this.updateMap();
  }

  import(): void {
    this.modalResume = true;
    this.updateMap();
  }

  private updateMap(): void {
    const listRusAux: Array<RuImport> = [];
    this.listRusOk = [];
    this.listRusError = [];
    this.map.forEach((valor: Array<RuImport>) => {
      valor.forEach((ru) => {
        listRusAux.push(ru);
      });
    });
    this.listRus = listRusAux;
    this.listRus.forEach((ru) => {
      if (ru.valid) {
        this.listRusOk.push(ru);
      } else {
        this.listRusError.push(ru);
      }
    });
    this.numRus = this.listRus.length;
    this.numRusOk = this.listRusOk.length;
    this.numRusError = this.listRusError.length;
  }

  uploadButton(upload): void {
    const span = upload.el.nativeElement.querySelector('span');
    span.querySelector('input').click();
  }

  insertRus(): void {
    this.rusService.addRusImport(this.listRusOk).subscribe(
      () => {
        this.toastrService.success(this.translateService.instant('generic.dialog.delete.insert_succesful'));
        this.router.navigate(['/configuration/hierarchy/']);
      },
      (err) => {
        this.toastrService.error(
          this.translateService.instant('generic.message.tecnichal_error'),
          this.translateService.instant('generic.message.contact_admin')
        );
      }
    );
  }

  downloadExcelErrors(): void {
    this.rusService.downloadErrorReport(this.translateService.currentLang, this.listRusError).subscribe(
      (blob: any) => {
        Utils.downloadObject(blob, 'Error_Report.xlsx');
      },
      (err) => {
        this.toastrService.error(
          this.translateService.instant('generic.message.tecnichal_error'),
          this.translateService.instant('generic.message.contact_admin')
        );
      }
    );
  }
}`

**Comment by apozogar1** [comment]
Sorry, Yes, I execute with Window.

**Comment by allenhwkim** [comment]
Can you make the example simpler, which focus on faillure also not exposing your company asset?

**Comment by apozogar1** [comment]
i'm talking with a coworker for test another application, I will write in this post with my conclusion.
If it's necessary, you would close this issues.

**Comment by apozogar1** [comment]
Hi again, I know which the problem, when I have a component extends to astract, it failed:
![image](https://user-images.githubusercontent.com/61603778/109261690-8284b380-7800-11eb-8c06-7d090e038a0a.png)

Do you review?, your app its a great tool.

**Comment by allenhwkim** [comment]
For this case, the generator try to find `ViewAbstractComponent`, which is not related generating test code at all.
To avoid failure, You can replace this string to blank('') for test generation using `replacements` at README.md
