### ISSUE TITLE
cannot find module using alias

### ISSUE THREAD

**Issue by Viktor-Bredihin** [allenhwkim/ngentest#49]
![Screenshot from 2021-05-11 21-35-14](https://user-images.githubusercontent.com/2298048/117867274-d69c2180-b2a0-11eb-9d3a-a4e35218ef4d.png)
![Screenshot from 2021-05-11 21-34-49](https://user-images.githubusercontent.com/2298048/117867281-d7cd4e80-b2a0-11eb-9c4e-b697677ecec4.png)
When I run ngtest command for any file, which use import from alias - I get Cannot find module error

**Comment by allenhwkim** [comment]
ngentest generates tests **by looking at your code, a single file**, not all your app.
  Thus, any import error happens, replace the errorenous path to  something that works. 
  This replace happens internally while gentest runs. It means It does not change your code.

  Try use replacements
  // faking import for errorenous lib.
  replacements: [
    { from: '@shared/\.*', to: '@angular/core' }
  ]

**Comment by Viktor-Bredihin** [comment]
@allenhwkim 
not sure how it can help, with replacement I have this error
{ Error: Cannot find module 'model/financial-year/financial-year'
If I change
import { FinancialYear } from '@shared/model/financial-year/financial-year';
to
import { FinancialYear } from '../app/shared/model/financial-year/financial-year';
it works fine, but I can't replace all imports

**Comment by allenhwkim** [comment]
try this this in your config. I
```
  replacements: [
    { from: '@shared/\\.*', to: '' }
  ]
```

**Comment by VladBozhinovski** [comment]
@Viktor-Bredihin temporarily change url from @shared/... to ../../shared/ . Somehow ngentest doesn't recognize @ paths or src/app/.

**Comment by allenhwkim** [comment]
Please share your **minimal** .ts code, so that I can reproduce your error.
