### ISSUE TITLE
No Support for Arrow Functions?

### ISSUE THREAD

**Issue by ravituvar** [allenhwkim/ngentest#58]
we have arrow functions as below

functionName = () => {
  // SOME FUNCTION CODE
}

and It doesnt generate the unit tests cases for such methods/functions, anything can be done on this?

**Comment by allenhwkim** [comment]
Please provide a step to reproduce it.

**Comment by ravituvar** [comment]
If you have a arrow function for callbacks it doesn't generate the test for those functions

**Comment by allenhwkim** [comment]
The issue here is when you defined `a=()=>b;`, it's a variable not a
function
ngentest collects all functions to generate test, excluding variables for
now.
