### ISSUE TITLE
Bugs on new versions

### ISSUE THREAD

**Issue by daniarza** [allenhwkim/ngentest#70]
Hi there!

I want notice the team that i found two bugs on the last modifications.

1. **tsFilePath** is not defined, should be used **tsPath** instead.
<img width="611" alt="Screenshot 2023-09-04 at 09 47 08" src="https://github.com/allenhwkim/ngentest/assets/144027115/4a218ff5-aeca-4910-8e4f-7519172a9e50">

2. **Util.FRAMEWORK** never returns 'karma' value. It only returns 'jest' or true. Getter should be **static get FRAMEWORK() { return Util.__framework ?? 'jest'; }** or something similar.

<img width="558" alt="Screenshot 2023-09-04 at 09 50 13" src="https://github.com/allenhwkim/ngentest/assets/144027115/1617fe68-bb78-42ec-b913-3282ab08a8c3">

Thank you and regards,

Daniel.

**Comment by allenhwkim** [comment]
Thanks for reporting bugs.
Fixed and released new version 2.2.1
