### ISSUE TITLE
gentest vs. ngentest

### ISSUE THREAD

**Issue by richardbrammer** [allenhwkim/ngentest#9]
What is the difference between ngentest and gentest?

Can they be used for different hings? The documentation is not clear on this and could be improved to explain the differences, if there are any. If there are no differneces, why do both commands exist?

**Comment by allenhwkim** [comment]
they are the same as you see in the package.json.
Two commands are just for users' convenience. 
```
  "bin": {
    "gentest": "./index.js",
    "ngentest": "./index.js"
  },
```
